# Data preprocessing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing dataset

In [ ]:
dataset = pd.read_csv("./50_Startups.csv")


## encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical = ['State']

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), categorical)], remainder='passthrough')
encoded_data = ct.fit_transform(dataset)

X = np.array(encoded_data[: , :-1])
y = np.array(encoded_data[: , -1])

np.set_printoptions(suppress=True)
print(X)
print(y)

[[     0.        0.        1.   165349.2  136897.8  471784.1 ]
 [     1.        0.        0.   162597.7  151377.59 443898.53]
 [     0.        1.        0.   153441.51 101145.55 407934.54]
 [     0.        0.        1.   144372.41 118671.85 383199.62]
 [     0.        1.        0.   142107.34  91391.77 366168.42]
 [     0.        0.        1.   131876.9   99814.71 362861.36]
 [     1.        0.        0.   134615.46 147198.87 127716.82]
 [     0.        1.        0.   130298.13 145530.06 323876.68]
 [     0.        0.        1.   120542.52 148718.95 311613.29]
 [     1.        0.        0.   123334.88 108679.17 304981.62]
 [     0.        1.        0.   101913.08 110594.11 229160.95]
 [     1.        0.        0.   100671.96  91790.61 249744.55]
 [     0.        1.        0.    93863.75 127320.38 249839.44]
 [     1.        0.        0.    91992.39 135495.07 252664.93]
 [     0.        1.        0.   119943.24 156547.42 256512.92]
 [     0.        0.        1.   114523.61 122616.84 261

## splitting data into training and test set

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train)
print("\n")
print(X_test)
print("\n")
print(y_train)
print("\n")
print(y_test)

[[     1.        0.        0.    63408.86 129219.61  46085.25]
 [     1.        0.        0.    38558.51  82982.09 174999.3 ]
 [     0.        0.        1.    78389.47 153773.43 299737.29]
 [     0.        1.        0.    28663.76 127056.21 201126.82]
 [     0.        0.        1.    86419.7  153514.11      0.  ]
 [     1.        0.        0.    23640.93  96189.63 148001.11]
 [     1.        0.        0.        0.   116983.8   45173.06]
 [     0.        1.        0.    75328.87 144135.98 134050.07]
 [     0.        1.        0.    73994.56 122782.75 303319.26]
 [     1.        0.        0.    91992.39 135495.07 252664.93]
 [     0.        1.        0.    27892.92  84710.77 164470.71]
 [     0.        0.        1.    94657.16 145077.58 282574.31]
 [     0.        0.        1.     1000.23 124153.04   1903.93]
 [     0.        0.        1.    77044.01  99281.34 140574.81]
 [     0.        1.        0.    67532.53 105751.03 304768.73]
 [     0.        1.        0.   142107.34  91391.77 366

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
# print(len(X_train))
# print(len(y_train))

40
40


## predicting test result

In [54]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_pred), 1) ), 1))

[[114664.42 105008.31]
 [ 90593.16  96479.51]
 [ 75692.84  78239.91]
 [ 70221.89  81229.06]
 [179790.26 191050.39]
 [171576.92 182901.99]
 [ 49753.59  35673.41]
 [102276.66 101004.64]
 [ 58649.38  49490.75]
 [ 98272.03  97483.56]]


In [57]:
# Making a single prediction (for example the profit of a startup with R&D Spend = 160000, Administration Spend = 130000, Marketing Spend = 300000 and State = 'California')
print(regressor.predict([[1, 0, 0, 160000, 130000, 300000]]))

print(regressor.coef_)
print(regressor.intercept_)

[180892.25]
[-285.18  297.56  -12.38    0.77   -0.01    0.03]
49834.88507320514
